### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by KrunalGupta02** [MightyITExplorer/Website#10]
As user prefer to use the dark mode i would like to  add the dark mode functionality to the website for better user experience.

**Comment by sagnik3788** [comment]
i want to work on this under jwoc

**Comment by Harry629** [comment]
I want to work on this issue under JWOC

**Comment by gnaneshwar718** [comment]
I want to work under jwoc

**Comment by kaal-coder** [comment]
@KrunalGupta02 start working!

**Comment by kaal-coder** [comment]
Closing the issue since it's completed.
