### ISSUE TITLE
[Bug] The Offcanvas Navbar breaks in smaller screens

### ISSUE THREAD

**Issue by pooranjoyb** [MightyITExplorer/Website#100]
### Related Video of the bug : 

[demo15.webm](https://user-images.githubusercontent.com/90945182/222966216-b3029ada-8710-4280-acf8-09af10db072a.webm)

**Comment by kaal-coder** [comment]
@pooranjoyb you are good to go. Share a preview in the form of a screenshot/video of the changes made while making a PR.

**Comment by pooranjoyb** [comment]
okk, sure I will open a PR by tomorrow. P.S. Thanks for assigning. @kaal-coder
