### ISSUE TITLE
adding DarkMode

### ISSUE THREAD

**Issue by subratkumar46** [MightyITExplorer/Website#11]
I would like to add dark theme to the project. 
User will be able to switch between light and dark mode .

I want to work on this issue under JWOC
please assign this issue to me.

**Comment by mnik7044** [comment]
I would like to add dark theme. I want to work on this issue please assign me

**Comment by kaal-coder** [comment]
Hey @subratkumar46 @mnik7044 I have assigned. Start working and provide a sample video before making a PR.

**Comment by subratkumar46** [comment]
https://user-images.githubusercontent.com/100276349/218924454-55a2ab41-8b36-4532-ae5c-b3c327ef8ee7.mp4

Demo of DarkMode

**Comment by kaal-coder** [comment]
Good work @subratkumar46. you can raise a PR with proper documentation.

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by mnik7044** [comment]
Hey @kaal-coder is this issue resolved?

**Comment by kaal-coder** [comment]
@mnik7044 yes, [this](https://github.com/MightyITExplorer/Website/issues/11) one is resolved
