### ISSUE TITLE
Testimonial button issue

### ISSUE THREAD

**Issue by S-ishita** [MightyITExplorer/Website#111]
The testimonial view more button color not matches with website ui. I want to fix it. 

Please assign this issue to me under JWOC

**Comment by kaal-coder** [comment]
No need to fix the button. Remove the testimonial page itself and hover effect on the testimonial cards.
Can you do this @S-ishita ?

**Comment by S-ishita** [comment]
Okay so u want testimonials on homepage only with hover effects and delete the different testimonial page??

**Comment by kaal-coder** [comment]
Yes.

**Comment by kaal-coder** [comment]
Can I assign it to you @S-ishita ?

**Comment by S-ishita** [comment]
Yes please assign
