### ISSUE TITLE
Add header and footer in the testimonials page

### ISSUE THREAD

**Issue by zugzwang03** [MightyITExplorer/Website#113]
I want to add header and footer in the testimonials page under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/223402768-28d1ddf8-dc85-4e5d-a155-264e626fbe6f.png)

**Comment by khushimarothi** [comment]
@kaal-coder please assign it to me. as per rules you can assign only one issue to a mentee she has created another issue as well so please assign it to me.

**Comment by kaal-coder** [comment]
There is no need of any header and footer since the testimonial page is being removed and is there in the home page only.
