### ISSUE TITLE
BUG: make or add changes not present in all pages

### ISSUE THREAD

**Issue by zugzwang03** [MightyITExplorer/Website#114]
The link to make or add changes on the website is only present in the home page, not on the other pages like opportunities, tech updates, etc. I want to fix this bug under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/223404177-02be8e3d-5ae0-4477-bdb6-2ca527ac1261.png)

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC

**Comment by kaal-coder** [comment]
It is kept intentionally in the home page only.
