### ISSUE TITLE
Add a custom css scroll bar 

### ISSUE THREAD

**Issue by Arbtrage** [MightyITExplorer/Website#12]
Would like to add a custom css scrollbar which would improve the UI of the website.
@kaal-coder , please assign me this issue

**Comment by purbakundu** [comment]
i want to contribute

**Comment by kaal-coder** [comment]
@purbakundu @Arbtrage I have assigned the issue to you. Start working on it. Before raising a PR, you can send a sample video of the website. All The Best!

**Comment by Arbtrage** [comment]
@kaal-coder , is this okay ?
I have added the scroll bar in theme.css file , so it's effect is reflected on all pages.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/100552235/218923468-e7bc77cd-a297-4d4e-a76c-c5281216f39e.gif)

**Comment by AgnishaDe** [comment]
I want to contribute in  this under JWOC

**Comment by kaal-coder** [comment]
@Arbtrage okay, just update the repo and then raise a PR.

**Comment by kaal-coder** [comment]
> I want to contribute in this under JWOC

Sure raise an issue.
