### ISSUE TITLE
More interactive styling of opportunity section. Can do the same for other sections too.

### ISSUE THREAD

**Issue by rohhhit31** [MightyITExplorer/Website#13]
@kaal-coder Please assign me this issue.

**Comment by purbakundu** [comment]
i want to contribute in this

**Comment by Codey001** [comment]
i want to work on the issue

**Comment by AgnishaDe** [comment]
I want to contribute in this issue under JWOC

**Comment by kaal-coder** [comment]
@rohhhit31 go for it on all the pages except the home page. Before raising a PR, you can send a sample video of the website. All The Best!

**Comment by kaal-coder** [comment]
@purbakundu @Codey001 @AgnishaDe raise an issue and start working on it.

**Comment by rohhhit31** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/75921596/219051422-2e6f568c-7f42-4fc3-904a-794742f51ed4.gif)
@kaal-coder look into this.

**Comment by kaal-coder** [comment]
good work @rohhhit31
