### ISSUE TITLE
fix the position of navbar while scrolling

### ISSUE THREAD

**Issue by Neha00011** [MightyITExplorer/Website#14]
I want to fix the position of navbar fixed and add some css property so that its color will change while scrolling.
please assign this issue under JWOC.

**Comment by purbakundu** [comment]
i want to contribute in this

**Comment by Harry629** [comment]
I want to work on this issue under JWOC

**Comment by AgnishaDe** [comment]
I want to contribute in this under JWOC

**Comment by kaal-coder** [comment]
@Neha00011 @purbakundu @Harry629 go for it. Before raising a PR, you can send a sample video of the website. All The Best!

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Neha00011** [comment]
https://user-images.githubusercontent.com/112271756/219147604-06b9a2a6-fa27-4dbf-8aae-adba62c1b5de.mp4

@kaal-coder this is the demo video.

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me
