### ISSUE TITLE
Add more list/cards of opportunity and study materials

### ISSUE THREAD

**Issue by shloksuman** [MightyITExplorer/Website#16]
The opportunity and study material sections contains very limited numbers of info cards. So I would like to increase those with new list of opportunity and add more various tech stacks in study material section. 
Kindly assign this issue to me

**Comment by Harry629** [comment]
I want to work on this issue under JWOC

**Comment by kaal-coder** [comment]
Go for it @shloksuman @Harry629. Before raising a PR, you can send a sample video of the website. All The Best!

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by shloksuman** [comment]
@kaal-coder Here's the updated opportunity and studymaterials page : 

https://user-images.githubusercontent.com/77777064/219091264-32a532ba-e033-49da-a6e3-615ce56c08e5.mp4

Some drive links were not working earlier, I have UPDATED them as well!

**Comment by shloksuman** [comment]
@kaal-coder kindly respond so I can make the PR for respective changes.

**Comment by rko0211** [comment]
Please assign me this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by kaal-coder** [comment]
@shloksuman do u still wish to do the changes ?
n I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by kaal-coder** [comment]
@shloksuman do u still wish to do the changes ?

**Comment by shloksuman** [comment]
@kaal-coder I've done the changes. (attaching the demo video) . Raised a PR as well. [PR](https://github.com/MightyITExplorer/Website/pull/84)


https://user-images.githubusercontent.com/77777064/222416877-291a1962-4956-445b-9287-bee1ebc09df3.mp4
