### ISSUE TITLE
want to add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by anamikarawat2305** [MightyITExplorer/Website#17]
Please assign me this issue under JWOC

**Comment by Yogeshkarma** [comment]
I want to work on this issue under JWOC

**Comment by kaal-coder** [comment]
@anamikarawat2305 @Yogeshkarma go for it. Give your best efforts. All The Best!

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Engeniusam** [comment]
Working on this issue.

**Comment by anamikarawat2305** [comment]
> @anamikarawat2305 @Yogeshkarma go for it. Give your best efforts. All The Best!

I think you assigned this issue to 2 people at the same time and as one already completed this issue. so I have to do it again or not?

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
Anyone wants to do can let me know. @Engeniusam @Hritik1503 @anamikarawat2305

**Comment by anamikarawat2305** [comment]
@kaal-coder it's already done in this repo by somebody else.
