### ISSUE TITLE
Site icon link not working

### ISSUE THREAD

**Issue by EmberTSeal** [MightyITExplorer/Website#18]
From Tech Updates and Jobs pages, clicking on site icon leads to 404 error.

**Comment by EmberTSeal** [comment]
I want to work on this, I am a contributor under JWOC.

**Comment by Codey001** [comment]
i want to work on the issue under JWOC

**Comment by kaal-coder** [comment]
@EmberTSeal @Codey001 go for it.
Before raising a PR, you can send a sample video of the website. All The Best!
Also, fix some of the card icons under the opportunity and Study Materials categories that are not working.

**Comment by EmberTSeal** [comment]
All right, will get to it, thank you!

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by kaal-coder** [comment]
@deepbeatz ok. go for it.

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2023-02-15 20 48 11" src="https://user-images.githubusercontent.com/79015311/219070044-1543f57a-a95c-4ebb-b0b6-f4c993d9aa8c.png">
what to do after this??

**Comment by kaal-coder** [comment]
@deepbeatz provide a screen recording of website, where I can see the changes you have made.

**Comment by deepbeatz** [comment]
https://user-images.githubusercontent.com/79015311/219121934-992f1928-aaeb-4549-9dc9-2e93550f6afa.mp4

here it is sir

**Comment by kaal-coder** [comment]
@deepbeatz google form link to "subscribe us" button of nav-bar. Fix it

GForm Link - https://docs.google.com/forms/d/e/1FAIpQLSdSNw19LnaM6Ve99y43WduXSn92KIjI7txHShHhZcWcu2S07Q/viewform

**Comment by kaal-coder** [comment]
@deepbeatz Some of the card icons under opportunity and Study Materials category are not working. Try fixing it with any link. You can replace them with roadmaps

**Comment by deepbeatz** [comment]
i have already done that sir after creating the separate issue for it.
also i have already sent the pr for it

**Comment by kaal-coder** [comment]
do all these in one and not separate.
the reason being you just need to fix the links and not code much.

**Comment by deepbeatz** [comment]
so sir you are telling me to do these 2 changes together with the previous change (site icon link) in one pull request
So for this should i send you a different pr with all the 3 changes done??\

**Comment by kaal-coder** [comment]
yes all fixed minor issues in one single PR.

**Comment by deepbeatz** [comment]
ok will get back to you sir as soon as i can
good night

**Comment by Codey001** [comment]
here it is sir

https://user-images.githubusercontent.com/97532891/219277323-dcaf9817-9fc9-42a6-9923-4053a8433239.mp4

**Comment by kaal-coder** [comment]
Hey @Codey001. I just checked that the site icon is already functioning properly.

**Comment by Codey001** [comment]
in the opportunity and thech update section is showing error 404, kindly check that.
I had fixed that and the issue in the card icons also.

**Comment by deepbeatz** [comment]
the drive links linked with the cards under student materials page are not valid, sir can you please provide the correct drive links for each of the 6 cards so that i can replace them with the ones in the code???

**Comment by deepbeatz** [comment]
@Codey001 so how did you fix the icon links?

**Comment by deepbeatz** [comment]
@kaal-coder the drive links linked with the cards under student materials page are not valid, sir can you please provide the correct drive links for each of the 6 cards so that i can replace them with the ones in the code???

**Comment by Codey001** [comment]
@kaal-coder , Did you checked the issue. Shall I make the pr regarding the fixing?

**Comment by deepbeatz** [comment]
@kaal-coder sir can you please provide correct google drive links for the "study materials" page??
I just need to relace the links with the correct ones and then i will raise a final pr having all the changes as you instructed.
Earnestly waiting for your reply!!

**Comment by deepbeatz** [comment]
@kaal-coder sir??

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by ayushmorbar** [comment]
I would like to work on this issue under JWoC!
