### ISSUE TITLE
Icons change, redirect fix and form link

### ISSUE THREAD

**Issue by Priyanshu88** [MightyITExplorer/Website#21]
I want to work on this issue under JWOC.

**Comment by kaal-coder** [comment]
Replacing links would be good. But can you work on any other aspect that improves the website more.

**Comment by Priyanshu88** [comment]
Sure. Shall I change the links as I have tested it locally?

**Comment by kaal-coder** [comment]
Yes.

**Comment by kaal-coder** [comment]
@Priyanshu88 google form link to "subscribe us" button of nav-bar. Fix it

**Comment by kaal-coder** [comment]
@Priyanshu88 From Tech Updates and Jobs pages, clicking on site icon leads to 404 error.
Fix it too

**Comment by Priyanshu88** [comment]
Ok working on it. Can you please paste the google form link?

**Comment by kaal-coder** [comment]
> Ok working on it. Can you please paste the google form link?

https://docs.google.com/forms/d/e/1FAIpQLSdSNw19LnaM6Ve99y43WduXSn92KIjI7txHShHhZcWcu2S07Q/viewform

**Comment by Priyanshu88** [comment]
I have made changes in code. Everything is done.

**Comment by Priyanshu88** [comment]
My code is ready and locally tested. Can you please add labels as I would like to merge this solved issue under JWOC?
https://youtu.be/C3WECVbIF-Q

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task
