### ISSUE TITLE
improve the style of navbar

### ISSUE THREAD

**Issue by ArpitaSaga** [MightyITExplorer/Website#28]
Please assign me to this issue.
Under JWOC

**Comment by kaal-coder** [comment]
@ArpitaSaga go for it. Before raising a PR, you can send a sample video of the website. All The Best!

**Comment by ArpitaSaga** [comment]
Please add the difficulty level tag

**Comment by kaal-coder** [comment]
Would be assigned based on the enhancement done.

**Comment by realsh9dy** [comment]
can you assign me this issue. ig the time is over for the previous assignee according to the rules of JWOC Mentor's Manual

**Comment by kaal-coder** [comment]
@ArpitaSaga will you be able to complete today by 22:00 ?

**Comment by ArpitaSaga** [comment]
Yes It's done

**Comment by ArpitaSaga** [comment]
Yes, it's done. I'll just make the video and post it

**Comment by kaal-coder** [comment]
Great 👍

**Comment by ArpitaSaga** [comment]
Should I post the video here or mail you?

**Comment by kaal-coder** [comment]
Both works fine. Better if you can share here

**Comment by ArpitaSaga** [comment]
https://user-images.githubusercontent.com/91795726/219421462-10aa091f-48e1-4400-b773-be1e0313adf3.mp4

**Comment by kaal-coder** [comment]
Nice work. Can you confirm that your branch is updated. If not do so and let me know.

**Comment by ArpitaSaga** [comment]
Yes it's updated

**Comment by kaal-coder** [comment]
Okay. Raise a PR @ArpitaSaga

**Comment by ArpitaSaga** [comment]
I am getting some errors.
![error1](https://user-images.githubusercontent.com/91795726/219430451-b0c89a54-5fe9-4bf2-a0c7-998f6571be34.JPG)
What should I do?

**Comment by kaal-coder** [comment]
Try making a PR using GitHub directly then. 
Do asap so that others can continue improving it

**Comment by ArpitaSaga** [comment]
I have made the PR

**Comment by Code1705** [comment]
i want to contribute to this issue , please assign me under jwoc

**Comment by vatan-prakash** [comment]
I want to work on this issue under JWOC.

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by Code1705** [comment]
I want to make the navbar stylish  by making certain prominent changes , please assign me under JWOC

**Comment by kaal-coder** [comment]
@Code1705 you can go for it. Make sure to send a preview while making a PR.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Code1705** [comment]
I have committed the changes and created a PR , could you merge it please?
