### ISSUE TITLE
Change the color of the Subscribe button in the navbar .

### ISSUE THREAD

**Issue by Arbtrage** [MightyITExplorer/Website#29]
The subscribe button in the navbar does not look consistent with the subscribe button in the banner section .

![image](https://user-images.githubusercontent.com/100552235/219118964-ac30fdbd-57ec-49bd-8e18-12b4fd692816.png)

**Proposed Idea**: Want to change the color of the subscribe button to this so that it would look more consistent.

![image](https://user-images.githubusercontent.com/100552235/219119509-3e91765c-af63-4ba6-a36c-9e050950f2f8.png)

@kaal-coder , please assign me this issue .

**Comment by kaal-coder** [comment]
I could suggest you some more improvements and then I can assign you. Will that work fine ?

**Comment by Arbtrage** [comment]
Yes sure

**Comment by kaal-coder** [comment]
In your previous PR, the scrollup bar isn't coming in the home page, so try fixing it.
You can check in icognito tab or in your phone.
You can Change the color of the Subscribe button in the navbar as in the Proposed Idea.
Also try adding a better font style to the navbar.

If you could add a hover effect of color while going over the text, would be great. Make sure to add different effect according to light and dark mode.

If you are okay with the above, I would add suitable label to the issue.

**Comment by Arbtrage** [comment]
@kaal-coder ,
The scroll bar is working ig, please confirm .
And regarding the rest of the features I would be happy to do them .

**Comment by kaal-coder** [comment]
Okay. Assigning you then.

**Comment by Arbtrage** [comment]
@kaal-coder , please review the following,

- [x] Changed the subscribe us button in the navbar
- [x] Added Open Sans font in the navbar 
- [ ] Hover effect not added for the navbar

There was already a hover effect present , should I change it ?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/100552235/219288396-af45fd38-2d8b-465e-aeb5-953d02f7977e.gif)

**Comment by kaal-coder** [comment]
yeah you need to improve it like the font will have a gradient type background effect when hover is done

**Comment by Arbtrage** [comment]
@kaal-coder , Like the text should have some gradient effect on hover ?

**Comment by Arbtrage** [comment]
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/100552235/219441069-a586a9f0-79bf-4e6b-8686-8d3f305ac880.gif)

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by Atul-8115** [comment]
I would like to work on this issue please assign it to me

**Comment by manya0210** [comment]
Hello sir...I want to work on this issue under jwoc

**Comment by vatan-prakash** [comment]
I want to work on this issue under JWOC.

**Comment by kaal-coder** [comment]
@Arbtrage you are good to go for a pr if you have done this. just make sure you update the branch.

> ![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/100552235/219441069-a586a9f0-79bf-4e6b-8686-8d3f305ac880.gif) [ ![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/100552235/219441069-a586a9f0-79bf-4e6b-8686-8d3f305ac880.gif) ](https://user-images.githubusercontent.com/100552235/219441069-a586a9f0-79bf-4e6b-8686-8d3f305ac880.gif) [ ](https://user-images.githubusercontent.com/100552235/219441069-a586a9f0-79bf-4e6b-8686-8d3f305ac880.gif)

n I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by Arbtrage** [comment]
Sure will create a PR , hope u r well now @kaal-coder . :)
