### ISSUE TITLE
Add Scroll to Top Button

### ISSUE THREAD

**Issue by SattyamSamania** [MightyITExplorer/Website#31]
I want to add a Scroll to Top Button with the help of HTML, CSS and Javascript. If you think that would be helpful, kindly assign this issue to me. Thank you!

**Comment by kaal-coder** [comment]
Do you want to add the same scroll to top it in the home page as it is present in other pages ?

**Comment by SattyamSamania** [comment]
> Do you want to add the same scroll to top it in the home page as it is present in other pages ?

I can add different on home page or can add same button as your wish

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by SattyamSamania** [comment]
> > Do you want to add the same scroll to top it in the home page as it is present in other pages ?
> 
> I can add different on home page or can add same button as your wish

@kaal-coder Can I create PR by creating same button on the home page?

**Comment by kaal-coder** [comment]
@SattyamSamania add a new one in the home page. Must look and function in a better way than existing.
All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by SattyamSamania** [comment]
> @SattyamSamania add a new one in the home page. Must look and function in a better way than existing.
> All the best. Let me know if you don't want to do in case due to late response.
> 
> I'm sorry for being inactive, the reason for the same was due to some serious health issues.

@kaal-coder It's okay. No problem 😊  at all. I will make PR tomorrow. Is that OK?

**Comment by kaal-coder** [comment]
okay.

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me
