### ISSUE TITLE
Decrease the space of Bottom Nav

### ISSUE THREAD

**Issue by utkarsh006** [MightyITExplorer/Website#32]
The bottom nav bar occupies too much space on the website. Can I work on the issue under JWOC to make it more impressive?

**Comment by kaal-coder** [comment]
![image](https://user-images.githubusercontent.com/85815858/219279458-f670fa7e-752f-4913-8609-307a89604815.png)
do you wish to do changes here ?

**Comment by utkarsh006** [comment]
@kaal-coder Yes buddy it is occupying too much of space.

**Comment by kaal-coder** [comment]
yes you can work on it.
also improve the font style
and when user hovers over anything then a effect appears.

will that work fine and should I assign you ?

**Comment by utkarsh006** [comment]
@kaal-coder I can work upon it kindly assign it to me.

**Comment by kaal-coder** [comment]
great. Before making a PR, send a video of the changes you have done here.
 All the best !

**Comment by AK-shat-JAIN** [comment]
Hello @kaal-coder I want to work under this issue

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by vatan-prakash** [comment]
I want to work on this issue under JWOC.

**Comment by AK-shat-JAIN** [comment]
@kaal-coder It's been a long time since to solve such a little issue 
Please assign it to me as I am next one to comment

**Comment by kaal-coder** [comment]
@AK-shat-JAIN done

**Comment by AK-shat-JAIN** [comment]
Thanks @kaal-coder
