### ISSUE TITLE
Subscribe us button is not working after clicking it ;

### ISSUE THREAD

**Issue by Ritu-2001** [MightyITExplorer/Website#34]
after clicking subscribe us button it should be automatically go down to the subscribe section i want to work on it please assign me

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
add our google form in that part @Ritu-2001 

All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by deepbeatz** [comment]
@kaal-coder i want to work in this issue under jwoc

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me
