### ISSUE TITLE
Changes in footer of the website

### ISSUE THREAD

**Issue by suryanshsoni120** [MightyITExplorer/Website#35]
1. Social media icons are very small. 
2. On clicking an icon, the page should open in a new tab.
3. Contact Us link would look better on navbar. Position is wrong on footer.

**Comment by suryanshsoni120** [comment]
I would like to work on these issues under JWOC

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
@suryanshsoni120 you are good to go. 

All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by suryanshsoni120** [comment]
I have made the changes and raised a PR.

**Comment by kaal-coder** [comment]
@suryanshsoni120 can you share a preview of the changes you have made.

**Comment by suryanshsoni120** [comment]
1. Size of social media icons increased.
2. On clicking an icon, the page opens in a new tab.
3. Contact Us link shifted to the navbar. 

![image](https://user-images.githubusercontent.com/63662732/221375054-957bd960-9166-42b3-800f-9567f25fda0d.png)

**Comment by kaal-coder** [comment]
Is that send message button working. If not please make it link with mightyitexplorer@gmail.com

**Comment by suryanshsoni120** [comment]
Done with the send message button. Queries will be sent to the mail id provided.
