### ISSUE TITLE
Add custom scrollbar in Socials page

### ISSUE THREAD

**Issue by zugzwang03** [MightyITExplorer/Website#36]
![image](https://user-images.githubusercontent.com/95460021/219353716-79799163-8c24-479b-bbcf-7bb81dc3ce6c.png)
I want to add a custom scroll bar for this page under JWOC'23. @kaal-coder

**Comment by misswow** [comment]
please assign me this project under jwoc

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
since it's going into another website (repository), I request you not to do changes under jwoc in this issue. Find something in this repo itself. Thanks

I'm sorry for being inactive, the reason for the same was due to some serious health issues.
