### ISSUE TITLE
Design report a bug page.

### ISSUE THREAD

**Issue by ayushanand308** [MightyITExplorer/Website#38]
We can design a bug reporting page where we can submits our bugs and this will be stored in a form and can be sent as an email to the maintainer of the project.

**Comment by ayushanand308** [comment]
Please assign me this issue under JWOC.

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
@ayushanand308 you are good to go. All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by Awesomeasma** [comment]
@kaal-coder 
I would like to work on this issue under JWOC.

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by kaal-coder** [comment]
@Awesomeasma you are good to go. All the best.

**Comment by kaal-coder** [comment]
@mecivil you are good to go. Share a preview in the form of a screenshot/video of the changes made while making a PR.
