### ISSUE TITLE
Subscribe Us button on hover effect bug

### ISSUE THREAD

**Issue by AK-shat-JAIN** [MightyITExplorer/Website#40]
Subscribe button on hover if Change to Purple(Color scheme) Color it will look great.
Also if I Drag and drop from the button to somewhere else Button's Colour remains change That's a bug.

**Comment by misswow** [comment]
Please assign me this under jwoc

**Comment by AK-shat-JAIN** [comment]
This issue is opened by me So assign this to me

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task
