### ISSUE TITLE
Improvement in Dark Mode

### ISSUE THREAD

**Issue by psykat1116** [MightyITExplorer/Website#42]
The colors in the dark mode are not good and some element are not seen in dark mode. Hover Effects are not so good I will also fix this.
Please assign me to this project.
![Screenshot 2023-02-17 185136](https://user-images.githubusercontent.com/95569573/219663817-b287263c-5cf7-4c14-a1d8-f5631b548d32.png)

**Comment by psykat1116** [comment]
Please Assign me to this project so that i can improve the UI and take participate in JWoC

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by psykat1116** [comment]
This icon is showing in light mode but not in dark mode I want to fix this issue please assign me.

![Screenshot 2023-02-21 104525](https://user-images.githubusercontent.com/95569573/220253952-0e85d44e-23f0-4bc5-a392-9120a20ada3f.png)
![Screenshot 2023-02-21 104546](https://user-images.githubusercontent.com/95569573/220253955-dc3cc40c-a479-4103-9e54-54208bf8fdd0.png)

**Comment by kaal-coder** [comment]
@psykat1116 you are good to go. All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by psykat1116** [comment]
@kaal-coder No Problem I want to do it.
