### ISSUE TITLE
Shadow in Dark Mode

### ISSUE THREAD

**Issue by Saishreekouda** [MightyITExplorer/Website#45]
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/96722257/219787426-b76f63f7-8092-44e8-863c-007b7c2e98a9.png">
These shadows are very loud and can be reduced a little bit for a better design

**Comment by Saishreekouda** [comment]
I would like to make these changes

**Comment by Hritik1503** [comment]
I am interested to solve this issue please assign me this task

**Comment by kaal-coder** [comment]
@Saishreekouda good to go.
All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by Saishreekouda** [comment]
@kaal-coder I will work on it

**Comment by kaal-coder** [comment]
Great
