### ISSUE TITLE
Subscribe Button Linking Problem

### ISSUE THREAD

**Issue by swarnade** [MightyITExplorer/Website#46]
The Subscribe button Is Only Working on the Home Button Not On All Other Page  ,Since the HREF="#" Is Mentioned In Button . The HREF Should Be Changed To Correct Link.. #jwoc

**Comment by Frs2304** [comment]
Hi there! I would love to take on this issue. I have experience working with similar problems. Please assign me this issue.

**Comment by Hritik1503** [comment]
I would like to solve this issue please assign me this issue
