### ISSUE TITLE
Validating contact us form

### ISSUE THREAD

**Issue by harshit21-02** [MightyITExplorer/Website#48]
Validating form fields in contact us section

**Comment by harshit21-02** [comment]
please assign me this issue under jwoc

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by kaal-coder** [comment]
do you wish to make this working ?
![image](https://user-images.githubusercontent.com/85815858/221252204-725b738d-eb36-45f7-845a-625221bea1f7.png)

**Comment by kaal-coder** [comment]
@harshit21-02 @Hritik1503

**Comment by kaal-coder** [comment]
Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by harshit21-02** [comment]
Yes I can work on this

**Comment by kaal-coder** [comment]
@harshit21-02 I have assigned. You can go for it. Make sure you share a preview (recording/screenshot ) of the changes while making a PR.
Mighty IT email  - mightyitexplorer@gmail.com

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me
