### ISSUE TITLE
Footer links opening in same tab

### ISSUE THREAD

**Issue by ritika728** [MightyITExplorer/Website#51]
Hey @kaal-coder , I would like to open this issue under JWOC. The links of the footer (twitter, linkedin etc.) are opening in the same tab which makes it a little less user friendly. I wish to improve that.

**Comment by ritika728** [comment]
Hey @kaal-coder can I work on this issue ?

**Comment by kaal-coder** [comment]
okay

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.
