### ISSUE TITLE
Update UI of study material cards

### ISSUE THREAD

**Issue by khushimarothi** [MightyITExplorer/Website#52]
Want to improve the ui of cards on the study material page;
please assign under jwoc

**Comment by Aarav238** [comment]
i would like to work on it

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by kaal-coder** [comment]
@khushimarothi you are good to go.
All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by khushimarothi** [comment]
> @khushimarothi you are good to go. All the best. Let me know if you don't want to do in case due to late response.
> 
> I'm sorry for being inactive, the reason for the same was due to some serious health issues.

Thank you for assigning it. I will start working on it.

**Comment by kaal-coder** [comment]
Great !

**Comment by khushimarothi** [comment]
@kaal-coder please check your dm got some doubts.
