### ISSUE TITLE
Improve the cards in Opportunity section | Under JWOC 

### ISSUE THREAD

**Issue by anurag8546** [MightyITExplorer/Website#53]
<img width="891" alt="Screenshot 2023-02-24 005207" src="https://user-images.githubusercontent.com/76533034/221009178-7fdb7c42-69c9-46fc-8ca3-a1151dc3988a.png">

I'd like to improve these cards.

**Comment by anurag8546** [comment]
@kaal-coder , I'd like to work on it. Can you please assign it to me?

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc so i request you to please assign me

**Comment by kaal-coder** [comment]
@anurag8546 you are good to go.
All the best. Let me know if you don't want to do in case due to late response.

I'm sorry for being inactive, the reason for the same was due to some serious health issues.

**Comment by anurag8546** [comment]
Sure @kaal-coder, on it.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.
