### ISSUE TITLE
Improve follow us page

### ISSUE THREAD

**Issue by khushimarothi** [MightyITExplorer/Website#55]
Want to improve the follow us page and also add a back to home button.
please assign under JWOC

**Comment by Hritik1503** [comment]
I am interested to work on this issue under jwoc

**Comment by kaal-coder** [comment]
@khushimarothi actually they are different repository (website) and there is no need of home back button, hence I'm closing this issue.

**Comment by khushimarothi** [comment]
No I just don't wanted to add home button exactly.
Wanted something like redesigning ..turning buttons into cards and adding so creative icon to them.
It's okay if you don't want it😅
