### ISSUE TITLE
Navbar Color Transition Fixed

### ISSUE THREAD

**Issue by rohhhit31** [MightyITExplorer/Website#58]
Earlier when you load the website it load the chnaged color already and the moment you start scrolling it chnages it to white for 0.5 secd and than the required but generally it should load up with white and than after scrolling should change it.

**Comment by rohhhit31** [comment]
@kaal-coder assign me this issue under jwoc i found the reason of the issue i can fix it in no time.

**Comment by kaal-coder** [comment]
also fix the subscribe us button, link it with our google form.

**Comment by rohhhit31** [comment]
@kaal-coder done. merge it
