### ISSUE TITLE
Creating a contribution.md file

### ISSUE THREAD

**Issue by anamikarawat2305** [MightyITExplorer/Website#64]
I want to create a contribution guidelines file in which it shows how to contribute in this repo such as fork, clone etc.

**Comment by kaal-coder** [comment]
okay. also add that they should give a preview whenever they raise a pr. and when they raise an issue, they should explain it well.

**Comment by ghost** [comment]
i would like to work on this under jwoc

**Comment by anamikarawat2305** [comment]
It's already done!
