### ISSUE TITLE
Improve Overall navbar responsiveness for mobile view

### ISSUE THREAD

**Issue by TuhinBanerjee31** [MightyITExplorer/Website#65]
![Screenshot (17)](https://user-images.githubusercontent.com/76838565/221319368-042aa8ab-4156-4dff-b1c4-cc0037da9b90.png)

Need to fix the dark-mode button for the small screen viewer as it is getting hidden under the navbar options. It should be visible on the top.

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by kaal-coder** [comment]
Good to go. All the best. Do share a preview while making a PR.

**Comment by kaal-coder** [comment]
@TuhinBanerjee31 any updates ?

**Comment by TuhinBanerjee31** [comment]
Will positively update you by tonight.

**Comment by TuhinBanerjee31** [comment]
Have modified and fixed the responsiveness issue of the navbar for the small screen viewer. And enhanced the navbar UI minorly for large screen viewers and priorly for small screen viewers.
![Screenshot (41)](https://user-images.githubusercontent.com/76838565/222288326-121134f5-8e9c-4b70-bd46-fd1fe0a076ab.png)
![Screenshot (42)](https://user-images.githubusercontent.com/76838565/222288335-88d36ce1-44ea-4203-94ad-7c114074fc62.png)
