### ISSUE TITLE
Add Animation in Landing Page

### ISSUE THREAD

**Issue by AK-shat-JAIN** [MightyITExplorer/Website#72]
The landing page looks very normal
Want to add an animation effect in it such that the text "Might ITExplorer" will animate and come like in this website
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me. and after that it normally redirects to main page

**Comment by kaal-coder** [comment]
Good to go. All the best. Do share a preview while making a PR.

**Comment by AK-shat-JAIN** [comment]
Sr I have two doubts:

1)Sr should I make my animations in existing landing page this one 
![image](https://user-images.githubusercontent.com/84455686/221433273-82dd0e24-6bd8-4619-bd00-40c556acfeff.png)
or I can introduce a new landing page made from scratch by me

2)For text "Mighty ITExplorer" should I use font according to me or you  want me to take any particular font (Formal, cursive, Funky)
or you can guide me to choose from below ones

A)Inter
![image](https://user-images.githubusercontent.com/84455686/221433542-de858c66-720c-4356-a47b-8350ab1ec94e.png)
B)K2D
![image](https://user-images.githubusercontent.com/84455686/221433595-4a446a42-9009-4cac-be0b-2c14431b612d.png)
C)Mansalva
![image](https://user-images.githubusercontent.com/84455686/221433619-00efbe20-f22f-4a9f-883b-e3a488208836.png)
D)Milonga
![image](https://user-images.githubusercontent.com/84455686/221433647-5fe9b11e-f8c6-43a0-b7d6-5518be945769.png)

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by AK-shat-JAIN** [comment]
@kaal-coder Please relpy

**Comment by kaal-coder** [comment]
@AK-shat-JAIN 
D)Milonga
Also place the logo coming in animation. You will be given enough time and if you do work on it in the best possible way would increase the level to hard. All the best.

**Comment by kaal-coder** [comment]
@AK-shat-JAIN Imagine yourself as a team member and think how the splash screen should be. keep the design and animation in between of something completely formal to completely stylish.

**Comment by AK-shat-JAIN** [comment]
> @AK-shat-JAIN D)Milonga Also place the logo coming in animation. You will be given enough time and if you do work on it in the best possible way would increase the level to hard. All the best.

Ok sr Thanks for this I will generate PR before tomorrow's morning please clear my one more question
can I remove text "Aim Act Acheve" from landing page or reduce logo and this text size so to get some place for animation??

**Comment by AK-shat-JAIN** [comment]
> 

I will put my best for this landing page to look awesome 🌟

**Comment by kaal-coder** [comment]
dont remove the text "Aim Act Acheve" and logo size can be reduced.

**Comment by AK-shat-JAIN** [comment]
ok sr I will Resize them

**Comment by kaal-coder** [comment]
@AK-shat-JAIN please have a look in the PR. the changes aren't reflecting.

**Comment by AK-shat-JAIN** [comment]
@kaal-coder Sr
Please try to host website from landing.htm page instead of index.html
