### ISSUE TITLE
Add testimonial 

### ISSUE THREAD

**Issue by Neha00011** [MightyITExplorer/Website#74]
I want to add a testimonial using html, css and swiper js.
Kindly assign this issue to me under JWOC.

**Comment by kaal-coder** [comment]
Good to go. All the best. Do share a preview while making a PR.

**Comment by garimadhiman** [comment]
I want to work for on this issue under jwoc community, please assign me

**Comment by DeepanshuRohilla15** [comment]
I want to add a testimonial using html, css and js.
Kindly assign this issue to me under JWOC.
