### ISSUE TITLE
fix #Testimonials Section

### ISSUE THREAD

**Issue by kaal-coder** [MightyITExplorer/Website#81]
Remove a separate page that has been created for testimonial and add it to home page.

**Comment by Aarav238** [comment]
I would like to work on it under JWOC . Please assign this to me @kaal-coder .

**Comment by PurviSaini** [comment]
Could I work on this issue under JWOC?

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by kaal-coder** [comment]
@Aarav238 you are good to go. All the best.

**Comment by kaal-coder** [comment]
@Aarav238 reminder to complete the assigned task by EOD, else it will be shifted to someone else.
