### ISSUE TITLE
improve #Testimonials card 

### ISSUE THREAD

**Issue by kaal-coder** [MightyITExplorer/Website#82]
Improve the Testimonials cards and make it in the similar design as the website.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by Aarav238** [comment]
i would like to work on it under JWOC @kaal-coder

**Comment by mecivil** [comment]
I would like to work on this issue under JWOC

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by kaal-coder** [comment]
@Awesomeasma you are good to go. All the best.

**Comment by kaal-coder** [comment]
@Awesomeasma reminder to complete the assigned task by EOD, else it will be shifted to someone else.

**Comment by Awesomeasma** [comment]
> @Awesomeasma reminder to complete the assigned task by EOD, else it will be shifted to someone else.

@kaal-coder  I have already submitted the PR, this afternoon.

**Comment by kaal-coder** [comment]
https://github.com/MightyITExplorer/Website/pull/96#issuecomment-1455119880

this section is there on the testimonial page or in the home page itself.
Also, how many cards are there. There should be atleast 4
I need it in the home page itself.
Also please add some random images.

**Comment by Awesomeasma** [comment]
> [#96 (comment)](https://github.com/MightyITExplorer/Website/pull/96#issuecomment-1455119880)
> 
> this section is there on the testimonial page or in the home page itself. Also, how many cards are there. There should be atleast 4 I need it in the home page itself. Also please add some random images.

@kaal-coder 
I have updated the changes.. please review it.

**Comment by kaal-coder** [comment]
Please make a single PR @Awesomeasma 
Also, have you removed the testimonial page that wasn't working and the samples you have shown are in the home page. Right ?

**Comment by Awesomeasma** [comment]
> Please make a single PR @Awesomeasma Also, have you removed the testimonial page that wasn't working and the samples you have shown are in the home page. Right ?

Ok sir, I'll make a single PR. U mean u want these cards to display in the home page, above the 'contact us' section ?

**Comment by kaal-coder** [comment]
Yes in the home page and above the 'contact us' section .

**Comment by Awesomeasma** [comment]
@kaal-coder 
It's done sir. please review my PR #104 
![updated-testimonial](https://user-images.githubusercontent.com/86073340/223074200-6166518e-f727-46fa-90ed-3a5e05588433.png)
