### ISSUE TITLE
Update the footer to enable opening links in a new tab

### ISSUE THREAD

**Issue by tmsagarofficial** [MightyITExplorer/Website#85]
I Observed that when clicked on social media links which are after the subscribe part upon clicking open in the same tab as the active tab...

I wanted to make all these links open in new tab as that would ease out and will be convenient to use the site after following up on socials rather than user has to go to previous tab to get back to the site.

![image](https://user-images.githubusercontent.com/110724849/222430340-09f724d9-1e2a-460a-a94b-9f02e15ae4d8.png)

**Comment by tmsagarofficial** [comment]
Also would love to update this 
![image](https://user-images.githubusercontent.com/110724849/222430659-e24fbfa7-90e9-40aa-affe-2ad4cc7f5af5.png)

**Comment by tmsagarofficial** [comment]
pls let me know about the same ☝🏼 @kaal-coder

**Comment by kaal-coder** [comment]
@tmsagarofficial you are good to go. All the best.

**Comment by kaal-coder** [comment]
@tmsagarofficial please complete the issues assigned to you ASAP, else I have to transfer it to someone else.

**Comment by tmsagarofficial** [comment]
Will do it by EOD @kaal-coder

**Comment by kaal-coder** [comment]
Great @tmsagarofficial. I hope you do all the 3 assigned issues by EOD. 
Make sure you keep the branch updated while making a PR. And share a preview of the changes made in the form of a screenshot/video.

**Comment by tmsagarofficial** [comment]
Yeah will do that!
