### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by tmsagarofficial** [MightyITExplorer/Website#86]
I would love to work on this issue by updating a few things in the readme..

I Really think 
- Adding screenshots of the live project will be awesome 
- Also adding more social links on the readme file.
- Adding some text at the end of the readme.

pls let me know about the same and if i can work on this under jwoc

**Comment by tmsagarofficial** [comment]
pls let me know about the same ☝🏼 @kaal-coder

**Comment by kaal-coder** [comment]
@tmsagarofficial you are good to go. All the best.
