### ISSUE TITLE
Update few parts in the landing page site 

### ISSUE THREAD

**Issue by tmsagarofficial** [MightyITExplorer/Website#87]
I would love to work to fix this with your guidance .
The logos become invisible in dark mode 😅 
- light mode:
![image](https://user-images.githubusercontent.com/110724849/222436718-7b2ebdb3-0a72-4a0b-8a8a-ac40eb26648b.png)
- dark mode:
![image](https://user-images.githubusercontent.com/110724849/222436849-0c73e75d-b83a-4549-9a19-9549ebce176f.png)

Pls let me know about the same

**Comment by khushimarothi** [comment]
I am interested to work on this issue

**Comment by tmsagarofficial** [comment]
> I would love to work to fix this with your guidance . The logos become invisible in dark mode 😅
> 
> * light mode:
>   ![image](https://user-images.githubusercontent.com/110724849/222436718-7b2ebdb3-0a72-4a0b-8a8a-ac40eb26648b.png)
> * dark mode:
>   ![image](https://user-images.githubusercontent.com/110724849/222436849-0c73e75d-b83a-4549-9a19-9549ebce176f.png)
> 
> Pls let me know about the same

pls let me know about the same ☝🏼 @kaal-coder

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by kaal-coder** [comment]
@tmsagarofficial you are good to go. All the best.

**Comment by khushimarothi** [comment]
@kaal-coder you can't assign more than one issue to a person per project. This is what rule says.

**Comment by tmsagarofficial** [comment]
Can u pls close this issue ...
Thanks for letting me contribute
