### ISSUE TITLE
Links in opportunities page are opening in the same tab

### ISSUE THREAD

**Issue by tmsagarofficial** [MightyITExplorer/Website#88]
As said above the links when clicked on `complete details` opens the link in the same tab ...... which would be nice if it could be made to open in a new different tab.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/110724849/222439561-2e22faa9-03c2-464c-93d6-f965ed490b36.png">

also this link or has been moved or deleted 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/110724849/222439832-d3bb0593-d4a8-43ea-ae66-1822c98f7442.png">

pls let me know i wouldlove to work on this

**Comment by tmsagarofficial** [comment]
pls let me know about the same ☝🏼 @kaal-coder

**Comment by kaal-coder** [comment]
@tmsagarofficial not needed to fix this for now :)

**Comment by tmsagarofficial** [comment]
Thanks for letting me know 👍🏼

**Comment by tmsagarofficial** [comment]
What about that thing related to react js eth polygon......

DO u want me to remove this part from the page 
@kaal-coder
