### ISSUE TITLE
Improve Cards In opportunity page

### ISSUE THREAD

**Issue by AbhiPatel10** [MightyITExplorer/Website#91]
![image](https://user-images.githubusercontent.com/76242769/222810035-3f4a4d59-8180-4d8c-80ae-74593a9bc9da.png)

Between current cards, there are more unwanted places between cards, so we need to improve that card, as shown below. 

![image](https://user-images.githubusercontent.com/76242769/222810272-f9f55000-9b96-4405-918a-58051d21e148.png)

Please assign this issue to me under JWOC

**Comment by kaal-coder** [comment]
@AbhiPatel10 you are good to go. Based on the improvement the level MIGHT be upgraded. I expect you to give your best. Share a preview in the form of a screenshot/video of the changes made while making a PR.

**Comment by AbhiPatel10** [comment]
Okay thank you for assigning me

**Comment by kaal-coder** [comment]
Welcome @AbhiPatel10 
make sure you complete the assigned issue on time.

**Comment by AbhiPatel10** [comment]
Yes, working on it , almost done 👍

**Comment by kaal-coder** [comment]
@AbhiPatel10 the changes are not as upto the mark. I gave a medium tag since I was expecting a complete new design in the CARD(s).
Can you try making a new design by EOD, else I'll merge your PR with an easy tag.

**Comment by AbhiPatel10** [comment]
okay, you can merge with easy tag.
