### ISSUE TITLE
Add hovering effects on study materials cards

### ISSUE THREAD

**Issue by zugzwang03** [MightyITExplorer/Website#97]
I want to add hover effects like scaling, box shadow, border radius on hovering the cards in the study materials section under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/222950880-3f6551b2-d7d2-4ab3-bd04-33f5f188a0e3.png)

**Comment by kaal-coder** [comment]
@zugzwang03 you are good to go. Do share a preview in the form of a screenshot/video of the changes made.
